name: cloud_toq_system
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage:
  form_field_validator: ^1.1.0
  flutter_svg: ^1.1.3
  localize_and_translate: ^4.1.1
  datetime_picker_formfield: ^2.0.1
  introduction_screen: ^3.0.2
  pin_code_fields: ^7.4.0
  anim_search_bar: ^2.0.2
  flutter_colorpicker: ^1.0.3
  intl: ^0.17.0
  flutter_slidable: ^2.0.0
  image_picker: ^0.8.5+3
  enum_to_string: ^2.0.1
  http: ^0.13.5
  shared_preferences: ^2.0.15
  mockito: ^5.3.0
  uuid: ^3.0.4
  equatable: ^2.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
      - family: Tajawal
        fonts:
          - asset: assets/fonts/Tajawal-Medium.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #         weight: 700

